//= error exception

fun main() {
  let a = false;
  assert(a);
}
