//= error code 2

fun main() {
    std::exit(2I);
}