//= error exception

fun main() {
    do {
        testThrowFromNativeButNotThrows(true);
    } catch e: Exception {
        assert(false);
    }
}