//= vm-args "--gc-verify"
//= stdout "b (tests/stacktrace/print-stack-trace2.dora:19:10)\na (tests/stacktrace/print-stack-trace2.dora:15:10)\nmain (tests/stacktrace/print-stack-trace2.dora:5:11)\n"

fn main() {
  let e = a();

  // this should test if backtrace in Exception is created the right way
  // by retrieveStackTrace (as Array[Int32])
  std::forceCollect();

  e.print();
}

fn a(): std::Stacktrace {
  return b();
}

fn b(): std::Stacktrace {
  return std::Stacktrace::new();
}
